server:
  port: 9601
spring:
  application:
    name: api-getway
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      #defaultZone: http://dmxiaoshen:123@eureka-master:8001/eureka,http://dmxiaoshen:123@eureka-slave:8002/eureka
      defaultZone: http://dmxiaoshen:123@localhost:8888/eureka
    register-with-eureka: true
zuul:
  routes:
   ft-a: /serviceA/**