server:
  port: 8887
spring:
  application:
    name: config-center
  cloud:
    config:
      server:
        git:
          uri: https://rep.360taihe.com/fengdai/env.git
          username: hushengen
          password: hsg123456
          default-label: master
encrypt:
  key: ueuk%33!
security:
  basic:
    enabled: true
  user:
    name: hushengen
    password: 123456

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://dmxiaoshen:123@localhost:8888/eureka
    register-with-eureka: true